import "./globals.css";
import { Inter } from "next/font/google";
import { Roboto } from "next/font/google";

import ThemeRegistry from "@/components/ThemeRegistry/ThemeRegistry";
import Box from "@mui/material/Box";

import { DRAWER_WIDTH } from "@/styles/Styles";

import { SessionProvider } from "next-auth/react"
import NavbarMUI from "@/ui/NavbarMUI";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <SessionProvider>
        <ThemeRegistry>
          <NavbarMUI>
            {children}
          </NavbarMUI>
        </ThemeRegistry>
        </SessionProvider>
      </body>
    </html>
  );
}
